extern RegisterClassA:          proc
extern CreateWindowExA:         proc
extern ShowWindow:              proc
extern UpdateWindow:            proc
extern GetMessageA:             proc
extern TranslateMessage:        proc
extern DispatchMessageA:        proc
extern HeapAlloc:               proc
extern HeapFree:                proc
extern PostQuitMessage:         proc
extern DefWindowProcA:          proc
extern SendMessageA:            proc
extern GetScrollInfo:           proc
extern SelectObject:            proc
extern GetTextMetricsA:         proc
extern GetDC:                   proc
extern ReleaseDC:               proc
extern SetWindowPos:            proc
extern SetWindowTextA:          proc
extern ChooseFontA:             proc
extern CreateFontIndirectA:     proc
extern CreateFileA:             proc
extern ReadFile:                proc
extern WriteFile:               proc
extern CloseHandle:             proc
extern GetFileSize:             proc
extern GetWindowTextLengthA:    proc
extern GetWindowTextA:          proc
extern GetClientRect:           proc
extern SetTextColor:            proc
extern SetBkMode:               proc
extern GetOpenFileNameA:        proc
extern GetSaveFileNameA:        proc
extern EnableMenuItem:          proc
extern PostMessageA:            proc
extern GetProcessHeap:          proc
extern LoadCursorA:             proc
extern LoadIconA:               proc
extern GetMenu:                 proc
extern GetSysColor:             proc
extern CreateSolidBrush:        proc
extern CreateFontA:             proc
extern SetWindowLongPtrA:       proc
extern GetModuleHandleA:        proc
extern ExitProcess:             proc